name: Fetch latest tank + GNSS → latest.json

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/2 * * * *"  

permissions:
  contents: write

jobs:
  pull-and-publish:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      S3_BUCKET_PARQUET:     ${{ secrets.S3_BUCKET_PARQUET }}
      PREFIX:                ${{ secrets.S3_PREFIX }}    
      GNSS_PREFIX:           ${{ vars.GNSS_PREFIX }}     

      A1_EMPTY:              ${{ vars.A1_EMPTY }}
      A1_FULL:               ${{ vars.A1_FULL }}
      LITRES_EMPTY:          ${{ vars.LITRES_EMPTY }}
      LITRES_FULL:           ${{ vars.LITRES_FULL }}

    steps:
      - uses: actions/checkout@v4

      - name: Sanity check workspace
        run: |
          echo "workspace: $GITHUB_WORKSPACE"
          ls -la
          test -f scripts/fetch_latest.py || (echo "scripts/fetch_latest.py not found" && exit 1)


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pandas pyarrow

      - name: Fetch newest Analog + GNSS and write latest.json
        run: python scripts/fetch_latest.py

      - name: Commit latest.json (if changed)
        run: |
          if git status --porcelain | grep -q "latest.json"; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreplygithub.com"
            git add latest.json
            git commit -m "data: update latest.json"
            git push
          else
            echo "No changes to commit."
